on: 
    push:
      branches:
        - main
    workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs: 
    deploy: 
        runs-on: ubuntu-latest
        steps:
        -   id: build-publish
            uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
            with: 
                path: dist/examples/browser